In [1]:
import pandas as pd
import numpy as np

In [2]:
data_pandas = pd.read_csv("mushrooms.csv")

In [3]:
data_pandas.head(10)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   
5     e         x           y         y       t    a               f   
6     e         b           s         w       t    a               f   
7     e         b           y         w       t    l               f   
8     p         x           y         w       t    p               f   
9     e         b           s         y       t    a               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   
5            c         b          n  ...                        s   
6            c         b          g  ...                        s   
7            c         b          n  ...                        s   
8            c         n          p  ...                        s   
9            c         b          g  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

In [4]:
data_pandas["class"].unique()

array(['p', 'e'], dtype=object)

In [5]:
keys = data_pandas.keys()

In [6]:
keys

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [7]:
num_features = len(keys)

In [8]:
num_str = data_pandas.size // num_features

In [9]:
num_str

8124

In [10]:
data_numpy = np.array([[0 for i in range(num_features)] for j in range(num_str)])

In [11]:
data_numpy

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
data_numpy.shape

(8124, 23)

In [13]:
letters_to_nums = []
nums_to_letters = []
for i in keys:
    dic1 = {}
    dic2 = {}
    iterat = 0
    #print(i)
    for j in data_pandas[i].unique():
        dic1[j] = iterat
        dic2[iterat] = j
        iterat += 1
    letters_to_nums.append(dic1)
    nums_to_letters.append(dic2)

In [14]:
letters_to_nums[0:3]
    

[{'p': 0, 'e': 1},
 {'x': 0, 'b': 1, 's': 2, 'f': 3, 'k': 4, 'c': 5},
 {'s': 0, 'y': 1, 'f': 2, 'g': 3}]

In [15]:
nums_to_letters[0:3]

[{0: 'p', 1: 'e'},
 {0: 'x', 1: 'b', 2: 's', 3: 'f', 4: 'k', 5: 'c'},
 {0: 's', 1: 'y', 2: 'f', 3: 'g'}]

In [16]:
for i in range(num_str):
    for j in range(num_features):
        #print(data_pandas.iloc(0)[j,i])
        data_numpy[i,j] = letters_to_nums[j][data_pandas.iloc(0)[i, j]]

In [17]:
data_numpy

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 2],
       ...,
       [1, 3, 0, ..., 8, 5, 6],
       [0, 4, 1, ..., 4, 3, 6],
       [1, 0, 0, ..., 6, 5, 6]])

In [18]:
Y = np.array(data_numpy[:,0])

In [19]:
Y

array([0, 1, 1, ..., 1, 0, 1])

In [20]:
data_numpy = np.delete(data_numpy, 0, axis=1)

In [21]:
data_numpy

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 1, 1],
       [1, 0, 2, ..., 1, 1, 2],
       ...,
       [3, 0, 0, ..., 8, 5, 6],
       [4, 1, 0, ..., 4, 3, 6],
       [0, 0, 0, ..., 6, 5, 6]])

In [131]:
data_numpy.shape

(8124, 22)

In [132]:
from keras.models import Sequential
#нейронная сеть, слои которой соединены друг с другом

from keras.layers import Dense
#тип слоев, когда нейроны предыдущего уровня соединяются со всеми нейронами следующего уровня

from keras.utils import np_utils
#утилиты для numpy

import tensorflow as tf
import keras
from sklearn.model_selection import train_test_split

In [133]:
print(len(keys))

23


In [134]:
X_train, X_test, y_train, y_test = train_test_split(data_numpy, Y, test_size=0.3)

In [135]:
y_train 

array([0, 1, 0, ..., 1, 0, 0])

In [136]:
np.random.seed(42)

In [137]:
#clf = KNeighborsClassifier(n_neighbors=5, algorithm='brute')

In [138]:

#%time clf.fit(X_train, y_train)

In [139]:
#%time res = clf.predict(X_test)
#res

In [140]:
#clf.score(X_test, y_test)

In [173]:
model = Sequential()


In [174]:
model.add(Dense(800, input_dim = 22, init = "normal", activation = "relu"))


/home/natalya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(800, input_dim=22, activation="relu", kernel_initializer="normal")`
  """Entry point for launching an IPython kernel.


In [175]:
model.add(Dense(800, input_dim = 22, init = "normal", activation = "relu"))


/home/natalya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(800, input_dim=22, activation="relu", kernel_initializer="normal")`
  """Entry point for launching an IPython kernel.


In [176]:
model.add(Dense(2, init="normal", activation="softmax"))


/home/natalya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(2, activation="softmax", kernel_initializer="normal")`
  """Entry point for launching an IPython kernel.


In [177]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="SGD", metrics=["accuracy"])


In [178]:
print(model.summary())


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_26 (Dense)             (None, 800)               18400     
_________________________________________________________________
dense_27 (Dense)             (None, 800)               640800    
_________________________________________________________________
dense_28 (Dense)             (None, 2)                 1602      
Total params: 660,802
Trainable params: 660,802
Non-trainable params: 0
_________________________________________________________________
None


In [179]:
model.fit(X_train, y_train, batch_size=200, nb_epoch=100, verbose=1)


/home/natalya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
5686/5686 [==============================] - 1s 172us/step - loss: 0.4995 - acc: 0.7884
Epoch 2/100
5686/5686 [==============================] - 1s 133us/step - loss: 0.3524 - acc: 0.8765
Epoch 3/100
5686/5686 [==============================] - 1s 127us/step - loss: 0.2901 - acc: 0.8991
Epoch 4/100
5686/5686 [==============================] - 1s 121us/step - loss: 0.2507 - acc: 0.9147
Epoch 5/100
5686/5686 [==============================] - 1s 127us/step - loss: 0.2221 - acc: 0.9279
Epoch 6/100
5686/5686 [==============================] - 1s 123us/step - loss: 0.1995 - acc: 0.9346
Epoch 7/100
5686/5686 [==============================] - 1s 129us/step - loss: 0.1814 - acc: 0.9416
Epoch 8/100
5686/5686 [==============================] - 1s 125us/step - loss: 0.1661 - acc: 0.9471
Epoch 9/100
5686/5686 [==============================] - 1s 132us/step - loss: 0.1530 - acc: 0.9516
Epoch 10/100
5686/5686 [==============================] - 1s 127us/step - loss: 0.1418 - acc: 0.9553

5686/5686 [==============================] - 1s 128us/step - loss: 0.0153 - acc: 0.9988
Epoch 83/100
5686/5686 [==============================] - 1s 119us/step - loss: 0.0150 - acc: 0.9989
Epoch 84/100
5686/5686 [==============================] - 1s 119us/step - loss: 0.0148 - acc: 0.9989
Epoch 85/100
5686/5686 [==============================] - 1s 122us/step - loss: 0.0146 - acc: 0.9989
Epoch 86/100
5686/5686 [==============================] - 1s 121us/step - loss: 0.0143 - acc: 0.9991
Epoch 87/100
5686/5686 [==============================] - 1s 121us/step - loss: 0.0141 - acc: 0.9993
Epoch 88/100
5686/5686 [==============================] - 1s 123us/step - loss: 0.0139 - acc: 0.9991
Epoch 89/100
5686/5686 [==============================] - 1s 120us/step - loss: 0.0137 - acc: 0.9991
Epoch 90/100
5686/5686 [==============================] - 1s 123us/step - loss: 0.0135 - acc: 0.9991
Epoch 91/100
5686/5686 [==============================] - 1s 121us/step - loss: 0.0133 - acc: 0.9991
Epo

In [181]:
predictions = model.predict(X_test)

In [182]:
predictions


array([[1.9635295e-03, 9.9803644e-01],
       [9.9996388e-01, 3.6157897e-05],
       [4.9020699e-04, 9.9950981e-01],
       ...,
       [9.9975485e-01, 2.4517841e-04],
       [4.4817678e-03, 9.9551827e-01],
       [9.9998236e-01, 1.7700766e-05]], dtype=float32)

In [183]:
res = predictions.argmax(axis=1)

In [184]:
res

array([1, 0, 1, ..., 0, 1, 0])

In [185]:
Score = 0
for i in range(len(res)):
    Score += (res[i] == y_test[i])

In [186]:
len(res)

2438

In [187]:
len(y_test)

2438

In [188]:
Score / len(res)

0.9995898277276456