In [2]:
import pandas as pd
import numpy as np

In [3]:
data_pandas = pd.read_csv("mushrooms.csv")

In [4]:
data_pandas.head(10)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   
5     e         x           y         y       t    a               f   
6     e         b           s         w       t    a               f   
7     e         b           y         w       t    l               f   
8     p         x           y         w       t    p               f   
9     e         b           s         y       t    a               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   
5            c         b          n  ...                        s   
6            c         b          g  ...                        s   
7            c         b          n  ...                        s   
8            c         n          p  ...                        s   
9            c         b          g  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

In [5]:
data_pandas["class"].unique()

array(['p', 'e'], dtype=object)

In [6]:
keys = data_pandas.keys()

In [7]:
keys

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [8]:
num_features = len(keys)

In [9]:
num_str = data_pandas.size // num_features

In [10]:
num_str

8124

In [11]:
data_numpy = np.array([[0 for i in range(num_features)] for j in range(num_str)])

In [12]:
data_numpy

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
data_numpy.shape

(8124, 23)

In [14]:
letters_to_nums = []
nums_to_letters = []
for i in keys:
    dic1 = {}
    dic2 = {}
    iterat = 0
    #print(i)
    for j in data_pandas[i].unique():
        dic1[j] = iterat
        dic2[iterat] = j
        iterat += 1
    letters_to_nums.append(dic1)
    nums_to_letters.append(dic2)

In [15]:
letters_to_nums[0:3]
    

[{'p': 0, 'e': 1},
 {'x': 0, 'b': 1, 's': 2, 'f': 3, 'k': 4, 'c': 5},
 {'s': 0, 'y': 1, 'f': 2, 'g': 3}]

In [16]:
nums_to_letters[0:3]

[{0: 'p', 1: 'e'},
 {0: 'x', 1: 'b', 2: 's', 3: 'f', 4: 'k', 5: 'c'},
 {0: 's', 1: 'y', 2: 'f', 3: 'g'}]

In [17]:
for i in range(num_str):
    for j in range(num_features):
        #print(data_pandas.iloc(0)[j,i])
        data_numpy[i,j] = letters_to_nums[j][data_pandas.iloc(0)[i, j]]

In [18]:
data_numpy

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 2],
       ...,
       [1, 3, 0, ..., 8, 5, 6],
       [0, 4, 1, ..., 4, 3, 6],
       [1, 0, 0, ..., 6, 5, 6]])

In [19]:
Y = np.array(data_numpy[:,0])

In [20]:
Y

array([0, 1, 1, ..., 1, 0, 1])

In [21]:
data_numpy = np.delete(data_numpy, 0, axis=1)

In [22]:
data_numpy

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 1, 1],
       [1, 0, 2, ..., 1, 1, 2],
       ...,
       [3, 0, 0, ..., 8, 5, 6],
       [4, 1, 0, ..., 4, 3, 6],
       [0, 0, 0, ..., 6, 5, 6]])

In [26]:
from keras.models import Sequential
#нейронная сеть, слои которой соединены друг с другом

from keras.layers import Dense
#тип слоев, когда нейроны предыдущего уровня соединяются со всеми нейронами следующего уровня

from keras.utils import np_utils
#утилиты для numpy

import tensorflow as tf
import keras
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(data_numpy, Y, test_size=0.3)

In [28]:
y_train 

array([1, 0, 1, ..., 0, 0, 1])

In [30]:
import seaborn as sns
from sklearn import datasets
from sklearn.base import ClassifierMixin
from sklearn.datasets import fetch_mldata
from sklearn.neighbors.base import NeighborsBase, KNeighborsMixin, SupervisedIntegerMixin 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import KNeighborsClassifier

from sklearn import metrics
from sklearn.neighbors import KDTree
from operator import itemgetter

In [31]:
clf = KNeighborsClassifier(n_neighbors=5, algorithm='brute')

In [32]:

%time clf.fit(X_train, y_train)

CPU times: user 1.85 ms, sys: 0 ns, total: 1.85 ms
Wall time: 1.5 ms


KNeighborsClassifier(algorithm='brute', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [33]:
%time res = clf.predict(X_test)
res

CPU times: user 757 ms, sys: 89 ms, total: 846 ms
Wall time: 721 ms


array([0, 0, 0, ..., 0, 1, 1])

In [34]:
clf.score(X_test, y_test)

1.0